// Package main demonstrates Poseidon gRPC server with all 4 RPC patterns.
//
// Run: go run ./examples/grpc-server
// Test: grpcurl -plaintext -d '{"name":"World"}' localhost:9090 hello.HelloService/SayHello
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"log"
	"net"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/lodgvideon/poseidon-http-server/grpcserver"
	"github.com/lodgvideon/poseidon-http-server/server"
)

// --- Protobuf-compatible message structs ---
// In production these would be generated by protoc. Here we use JSON for clarity.

type HelloRequest struct {
	Name string `json:"name"`
}

type HelloResponse struct {
	Message string `json:"message"`
}

// --- Handlers ---

// SayHello: Unary RPC
func sayHello(_ context.Context, msg []byte) ([]byte, error) {
	var req HelloRequest
	if err := json.Unmarshal(msg, &req); err != nil {
		return nil, fmt.Errorf("invalid request: %w", err)
	}
	resp := HelloResponse{Message: "Hello, " + req.Name + "!"}
	return json.Marshal(resp)
}

// LotsOfReplies: Server-streaming RPC
func lotsOfReplies(_ context.Context, msg []byte, send grpcserver.StreamSender) error {
	var req HelloRequest
	if err := json.Unmarshal(msg, &req); err != nil {
		return err
	}
	for i := range 5 {
		resp := HelloResponse{Message: fmt.Sprintf("[%d] Hello, %s!", i+1, req.Name)}
		data, _ := json.Marshal(resp)
		if err := send(data); err != nil {
			return err
		}
		time.Sleep(200 * time.Millisecond)
	}
	return nil
}

// LotsOfGreetings: Client-streaming RPC
func lotsOfGreetings(_ context.Context, recv func() ([]byte, error)) ([]byte, error) {
	count := 0
	for {
		msg, err := recv()
		if err == io.EOF {
			break
		}
		if err != nil {
			return nil, err
		}
		var req HelloRequest
		if err := json.Unmarshal(msg, &req); err != nil {
			return nil, err
		}
		log.Printf("received greeting from: %s", req.Name)
		count++
	}
	resp := HelloResponse{Message: fmt.Sprintf("Received %d greetings!", count)}
	return json.Marshal(resp)
}

// BidiHello: Bidirectional streaming RPC
func bidiHello(_ context.Context, recv func() ([]byte, error), send grpcserver.StreamSender) error {
	for {
		msg, err := recv()
		if err == io.EOF {
			return nil
		}
		if err != nil {
			return err
		}
		var req HelloRequest
		if err := json.Unmarshal(msg, &req); err != nil {
			return err
		}
		resp := HelloResponse{Message: "Echo: " + req.Name}
		data, _ := json.Marshal(resp)
		if err := send(data); err != nil {
			return err
		}
	}
}

func main() {
	// --- Service registration ---
	reg := grpcserver.NewServiceRegistrar()
	reg.RegisterService(&grpcserver.ServiceDesc{
		Name: "hello.HelloService",
		Methods: []grpcserver.MethodDesc{
			{Name: "SayHello", UnaryHandler: sayHello},
			{Name: "LotsOfReplies", ServerStreamH: lotsOfReplies},
			{Name: "LotsOfGreetings", ClientStreamH: lotsOfGreetings},
			{Name: "BidiHello", BidiStreamH: bidiHello},
		},
	})

	// Enable gRPC server reflection so grpcurl list/describe work.
	reg.RegisterReflection()
	reg.RegisterFileDescriptorSet(helloFileDescriptor)

	// --- Poseidon server ---
	srv, err := server.NewServer(server.Options{
		Handler:       reg.Handler(),
		IdleTimeout:   60 * time.Second,
		StreamingBody: true,
	})
	if err != nil {
		log.Fatal(err)
	}

	ln, err := net.Listen("tcp", ":9090")
	if err != nil {
		log.Fatal(err)
	}

	ctx, cancel := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer cancel()

	go func() {
		log.Println("Poseidon gRPC server listening on :9090 (h2c)")
		if err := srv.Serve(ctx, ln); err != nil {
			log.Printf("serve: %v", err)
		}
	}()

	<-ctx.Done()
	log.Println("draining...")

	drainCtx, drainCancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer drainCancel()
	_ = srv.Shutdown(drainCtx)
	log.Println("bye 👋")
}
